In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Diabetes.csv")

In [3]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [5]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [6]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [7]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [10]:
X = scaler.fit_transform(X)

In [11]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [14]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [15]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

/opt/homebrew/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [16]:
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4618 - loss: 0.7256 - val_accuracy: 0.6753 - val_loss: 0.6450
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.6310 - loss: 0.6664 - val_accuracy: 0.7403 - val_loss: 0.5985
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6975 - loss: 0.6146 - val_accuracy: 0.7597 - val_loss: 0.5615
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7182 - loss: 0.5834 - val_accuracy: 0.7727 - val_loss: 0.5360
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.7128 - loss: 0.5652 - val_accuracy: 0.7857 - val_loss: 0.5167
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7311 - loss: 0.5400 - val_accuracy: 0.8182 - val_loss: 0.5002
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.7456 - loss: 0.5305 - val_accuracy: 0.8052 - val_loss: 0.4872
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7761 - loss: 0.4943 - val_accura

In [23]:
import keras_tuner as kt

In [24]:
def buildmodel(hp):
    model = Sequential()
    model.add(Dense(32, activation='relu', input_dim=8))
    model.add(Dense(1, activation='sigmoid'))

    optimizer=hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta'])

    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

    return model

In [25]:
tuner = kt.RandomSearch(buildmodel,
                        objective='val_accuracy',
                        max_trials=5)

In [26]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 4 Complete [00h 00m 01s]
val_accuracy: 0.5129870176315308

Best val_accuracy So Far: 0.8181818127632141
Total elapsed time: 00h 00m 02s


In [27]:
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

In [28]:
best_model = tuner.get_best_models(num_models=1)[0]
best_model.summary()

/opt/homebrew/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:415: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8081 - loss: 0.4088 - val_accuracy: 0.8312 - val_loss: 0.4423
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7933 - loss: 0.4191 - val_accuracy: 0.8312 - val_loss: 0.4448
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.8114 - loss: 0.3947 - val_accuracy: 0.8312 - val_loss: 0.4434
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.8069 - loss: 0.3986 - val_accuracy: 0.8312 - val_loss: 0.4437
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.8228 - loss: 0.3972 - val_accuracy: 0.8247 - val_loss: 0.4447
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.8096 - loss: 0.3999 - val_accuracy: 0.8247 - val_loss: 0.4448
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.8256 - loss: 0.4059 - val_accuracy: 0.8312 - val_loss: 0.4438
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.8357 - loss: 0.3772 - val_a

In [30]:
def buildmodel(hp):
    model = Sequential()

    units = hp.Int('units', min_value=8, max_value=128, step=8)

    model.add(Dense(32, activation='relu', input_dim=8))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

    return model

In [31]:
tuner = kt.RandomSearch(buildmodel,
                        objective='val_accuracy',
                        max_trials=5,
                        directory='mydir')

In [32]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 01s]
val_accuracy: 0.7207792401313782

Best val_accuracy So Far: 0.7662337422370911
Total elapsed time: 00h 00m 03s


In [33]:
def buildmodel(hp):
    model = Sequential()
    model.add(Dense(72, activation='relu', input_dim=8))

    for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
        model.add(Dense(72, activation='relu'))

    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

    return model

In [34]:
tuner = kt.RandomSearch(buildmodel,
                        objective='val_accuracy',
                        max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json


In [35]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [36]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8246 - loss: 0.3803 - val_accuracy: 0.8117 - val_loss: 0.4535
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8019 - loss: 0.3770 - val_accuracy: 0.8117 - val_loss: 0.4534
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.8263 - loss: 0.3680 - val_accuracy: 0.8117 - val_loss: 0.4534
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.8282 - loss: 0.3604 - val_accuracy: 0.8052 - val_loss: 0.4550
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.8031 - loss: 0.3952 - val_accuracy: 0.8052 - val_loss: 0.4543
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.8288 - loss: 0.3613 - val_accuracy: 0.8052 - val_loss: 0.4546
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.8009 - loss: 0.3840 - val_accuracy: 0.8052 - val_loss: 0.4540
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.8050 - loss: 0.3948 - val_acc

In [37]:
def buildmodel(hp):
    model = Sequential()
    counter = 0

    for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
        if counter == 0:
            model.add(
                Dense(
                    hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
                    activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']),
                    input_dim=8
            ))
            model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))
        else:
            model.add(
                Dense(
                    hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
                    activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']),
                    input_dim=8
            ))
            model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))

            counter += 1

    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer=hp.Choice('optimizer', values=['rmsprop', 'adam', 'sgd', 'nadam', 'adadelta']), loss='binary_crossentropy', metrics=['accuracy'])

    return model

In [38]:
tuner = kt.RandomSearch(buildmodel,
                        objective='val_accuracy',
                        max_trials=3)

Reloading Tuner from ./untitled_project/tuner0.json


In [39]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [40]:
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

In [41]:
best_hps

In [42]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=5, validation_data=(X_test, y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8275 - loss: 0.3682 - val_accuracy: 0.8117 - val_loss: 0.4626
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.8437 - loss: 0.3487 - val_accuracy: 0.8117 - val_loss: 0.4601
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.8218 - loss: 0.3839 - val_accuracy: 0.8117 - val_loss: 0.4599
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8318 - loss: 0.3605 - val_accuracy: 0.8117 - val_loss: 0.4606
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.8364 - loss: 0.3697 - val_accuracy: 0.8117 - val_loss: 0.4613
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.8275 - loss: 0.3730 - val_accuracy: 0.8052 - val_loss: 0.4673
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8210 - loss: 0.3732 - val_accuracy: 0.8117 - val_loss: 0.4630
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.8158 - loss: 0.3769 - val_accu